name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write
  issues: write

jobs:
  # Run tests on every push to main for early regression detection
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for commitlint
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: TypeScript check
        run: npm run ts-check

      - name: Lint
        run: npm run lint

      - name: Commitlint
        run: |
          # Only run commitlint on push events (not on release PRs)
          if [[ "${{ github.event_name }}" == "push" ]]; then
            npx commitlint --from HEAD~1 --to HEAD --verbose
          else
            echo "Skipping commitlint on non-push event"
          fi

      - name: Run tests
        run: npm test -- --watchAll=false

  release-please:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for release-please
      
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}

      # Optional: If you want to run additional steps after a release is created
      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      - name: Run post-release tests
        if: ${{ steps.release.outputs.release_created }}
        run: npm test -- --watchAll=false

      # You can add more steps here for publishing, deployment, etc.
      # For example, if you want to publish to npm, Expo, etc. 